
.. _sectionD:

Extensible Markup Language (XML) 1.1 https://www.w3.org/TR/xml11

Mathematical Markup Language (MathML) Version 2.0 https://www.w3.org/TR/MathML2/

Namespaces in XML 1.1 https://www.w3.org/TR/xml-names11/

RFC 2119: Key words for use in RFCs to Indicate Requirement Levels https://www.ietf.org/rfc/rfc2119.txt

Unicode 13.0.0 https://www.unicode.org/versions/Unicode13.0.0/

XML Information Set https://www.w3.org/TR/xml-infoset/

XML Linking Language (XLink) Version 1.1 https://www.w3.org/TR/xlink11/
