**Authors:**

Michael Clerx,
Michael T. Cooling,
Jonathan Cooper,
Alan Garny,
Keri Moyle,
David P. Nickerson,
Poul Nielsen, and
Hugh Sorby.

**Contributors:**

Koray Atalag,
David Brooks,
Edmund J. Crampin,
Jesús Carro Fernández,
Peter J. Hunter,
Gary R. Mirams, and
Maxwell L. Neal.

The authors also wish to acknowledge the significant contribution of the (discontinued) CellML 1.2 draft specification, much of the text of which was incorporated into this specification, although the semantics have changed considerably.
The CellML 1.2 specification was itself the result of a collaborative effort by a number of researchers during 2008-2011\:

Andrew K. Miller (who wrote the text reused here),
Randall Britten,
Jonathan Cooper,
Alan Garny,
Peter J. Hunter,
Justin Marsh,
Poul Nielsen,
David P. Nickerson, and
Hugh Sorby.

**Contact:** editors@cellml.org
