.. _inform_preamble:

This document is the informative version of the CellML 2.0 Specification, which combines the normative specification with examples and less formal explanations of CellML syntax and interpretation.
Readers may expand the "See more" blocks throughout this document to access each section of the informative version and see the relevant examples and links.

The official normative specification document is to download from: https://www.cellml.org/specifications/cellml_2.0/cellml_2_0_normative_specification.pdf 

.. include:: reference/acknowledgements.inc
