.. _inform_preamble:

This document is the normative version of the CellML Specification, defining the CellML syntax and the rules by which it should be used.
It is intended primarily for the developers of software tools which directly consume CellML syntax.
Users of CellML models may expand the "See more" blocks throughout this document to access the informative version and see examples.
Software-specific information is also available under their respective names or icons throughout the text. 

.. include:: reference/acknowledgements.inc
