.. _sectionD:

Extensible Markup Language (XML) 1.1 https://www.w3.org/TR/xml11

Mathematical Markup Language (MathML) Version 2.0 :mathml2spec:`https://www.w3.org/TR/MathML2/ <>`

Namespaces in XML 1.1 :xml_namespace_refs:`https://www.w3.org/TR/xml-names11/ <>`

RFC 2119: Key words for use in RFCs to Indicate Requirement Levels :rfc2119:`https://www.ietf.org/rfc/rfc2119.txt <>`

Unicode 13.0.0 :unicode13:`https://www.unicode.org/versions/Unicode13.0.0/ <>`

XML Information Set :xml_infoset:`https://www.w3.org/TR/xml-infoset/ <>`

XML Information Set 2004 :xml_infoset2004:`http://www.w3.org/TR/2004/REC-xml-infoset-20040204/ <>`

XML Linking Language (XLink) Version 1.1 https://www.w3.org/TR/xlink11/
