.. _sectionD:

.. _ref_xml_1_1:

1. Extensible Markup Language (XML) 1.1 :xml_1_1_display:`/`

.. _ref_mathml2:

2. Mathematical Markup Language (MathML) Version 2.0 :mathml2_display:`/`

.. _ref_xml_namespace_1_1:

3. Namespaces in XML 1.1 :xml_namespace_1_1_display:`/`

.. _ref_rfc2119:

4. RFC 2119: Key words for use in RFCs to Indicate Requirement Levels :rfc2119_display:`rfc2119.txt`

.. _ref_unicode:

5. Unicode 13.0.0 :unicode13_display:`/`

.. _ref_xml_infoset:

6. XML Information Set :xml_infoset_display:`/`

.. _ref_xlink:

7. XML Linking Language (XLink) Version 1.1 :xlink_display:`/`
