.. _sectionD:

.. [ref_xml_1_1] Extensible Markup Language (XML) 1.1 :xml_1_1_display:`/`

.. [ref_mathml2] Mathematical Markup Language (MathML) Version 2.0 :mathml2_display:`/`

.. [ref_xml_namespace_1_1] Namespaces in XML 1.1 :xml_namespace_1_1_display:`/`

.. [ref_rfc2119] RFC 2119: Key words for use in RFCs to Indicate Requirement Levels :rfc2119_display:`rfc2119.txt`

.. [ref_unicode] Unicode 13.0.0 :unicode13_display:`/`

.. [ref_xml_infoset] XML Information Set :xml_infoset_display:`/`

.. [ref_xlink] XML Linking Language (XLink) Version 1.1 :xlink_display:`/`

.. [1] testing
